version: '3'

services:
  chatroom:
    image: ${CHATROOM_TAG}
    container_name: chatroom
    ports:
      - 8081:8081
    networks:
      - mynetwork
    environment:
      - ENV=prod
      - TZ=Asia/Taipei
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 5M
    depends_on:
      - mysql
      - redis
      - elasticsearch

  mysql:
    image: mysql:5.7.26
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Taipei
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 5M
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute=\"SHOW DATABASES;\""
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - ${VOLUMES_PATH}/mysql:/var/lib/mysql

  redis:
    image: redis:5.0.5
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - mynetwork
    environment:
      - TZ=Asia/Taipei
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300
      - 9100:9100
    networks:
      - mynetwork
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - TZ=Asia/Taipei
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    healthcheck:
      test: "curl -XGET http://localhost:9200/_cat/health"
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - ${VOLUMES_PATH}/elasticsearch:/usr/share/elasticsearch/data

networks:
  mynetwork:
    driver: bridge
