version: '3'

services:
  auto-test:
    image: ${AUTO_TEST_TAG}
    container_name: auto-test
    networks:
      - mynetwork
    environment:
      - TZ=Asia/Taipei
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 5M

networks:
  mynetwork:
    driver: bridge
